name: CI
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.0

  unix:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-13, macos-14]

    steps:
    - uses: actions/checkout@v4

    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2

    - name: Install micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment-dev.yml

    - name: Cmake configure
      run: |
        cmake -B build -Werror=dev \
        ${CMAKE_ARGS} \
        -D CMAKE_BUILD_TYPE=Release \
        -D XWIDGETS_BUILD_TESTS=ON \
        -D CMAKE_PREFIX_PATH="${CONDA_PREFIX}" \
        -D CMAKE_INSTALL_PREFIX="${CONDA_PREFIX}"

    - name: Build
      run: cmake --build build/ --parallel 2

    - name: Test xwidgets
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 4
        max_attempts: 4
        shell: bash
        command: ctest --test-dir build/test --output-on-failure

    - name: Install xwidgets
      shell: bash -l -eo pipefail {0}
      run: cmake --install build/

#    - name: Test notebook
#      if: ${{ startsWith(matrix.os, 'ubuntu') }}
#      shell: bash -l -eo pipefail {0}
#      run: >
#        jupyter nbconvert
#        --to notebook
#        --output-dir "$(mktemp -d)/out.ipynb"
#        --execute
#        notebooks/xwidgets.ipynb

  win:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025]

    steps:
    - uses: actions/checkout@v4

    - name: Install micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        init-shell: cmd.exe
        environment-file: environment-dev.yml

    - name: Make build directory
      run: mkdir build

    - name: Cmake configure
      shell: cmd /C call {0}
      run: |
        cmake -B build -Werror=dev ^
         -G Ninja ^
         -D CMAKE_BUILD_TYPE=Release ^
         -D XWIDGETS_BUILD_TESTS=ON ^
         -D XWDIGETS_BUILD_TESTS=ON ^
         -D CMAKE_PREFIX_PATH="%CONDA_PREFIX%\Library" ^
         -D CMAKE_INSTALL_PREFIX="%CONDA_PREFIX%"

    - name: Build
      shell: cmd /C call {0}
      run: |
        set CL=/MP
        if %errorlevel% neq 0 exit /b %errorlevel%
        micromamba run -n xwidgets cmake --build build/ --parallel

    - name: Test xwidgets
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 4
        max_attempts: 4
        shell: cmd
        command: |
          set PATH=%CONDA_PREFIX%;%CONDA_PREFIX%\\Scripts;%CONDA_PREFIX%\\Library;%CONDA_PREFIX%\\Library\\bin;%PATH%
          ctest --test-dir build/test --output-on-failure
